server:
  port: 3625
logging:
  level:
    com.github.pondhia.ctrzit: debug
    org.springframework: warn
spring:
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
infra:
  docker:
    host: unix:///var/run/docker.sock
ctrzit:
  version: 0.0.1
  upload-path: uploads
  download-path: /attachments